// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.string().primaryKey().name("room_id"),
  hostIdentity: __t.identity().name("host_identity"),
  hostPeerId: __t.string().name("host_peer_id"),
  name: __t.string(),
  rulesetId: __t.string().name("ruleset_id"),
  rulesetHash: __t.string().name("ruleset_hash"),
  contentHash: __t.string().name("content_hash"),
  mapBundleId: __t.string().name("map_bundle_id"),
  playerCount: __t.u32().name("player_count"),
  maxPlayers: __t.u32().name("max_players"),
  transport: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  lastHeartbeat: __t.timestamp().name("last_heartbeat"),
});
