// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  membershipId: __t.string().primaryKey().name("membership_id"),
  roomId: __t.string().name("room_id"),
  peerIdentity: __t.identity().name("peer_identity"),
  peerId: __t.string().name("peer_id"),
  displayName: __t.string().name("display_name"),
  state: __t.string(),
  joinedAt: __t.timestamp().name("joined_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
