// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  signalId: __t.string().primaryKey().name("signal_id"),
  roomId: __t.string().name("room_id"),
  fromPeerId: __t.string().name("from_peer_id"),
  toPeerId: __t.string().name("to_peer_id"),
  signalKind: __t.string().name("signal_kind"),
  payloadJson: __t.string().name("payload_json"),
  createdAt: __t.timestamp().name("created_at"),
});
