// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const HostedRoom = __t.object("HostedRoom", {
  roomId: __t.string(),
  hostIdentity: __t.identity(),
  hostPeerId: __t.string(),
  name: __t.string(),
  rulesetId: __t.string(),
  rulesetHash: __t.string(),
  contentHash: __t.string(),
  mapBundleId: __t.string(),
  playerCount: __t.u32(),
  maxPlayers: __t.u32(),
  transport: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  lastHeartbeat: __t.timestamp(),
});
export type HostedRoom = __Infer<typeof HostedRoom>;

export const HostedRoomPeer = __t.object("HostedRoomPeer", {
  membershipId: __t.string(),
  roomId: __t.string(),
  peerIdentity: __t.identity(),
  peerId: __t.string(),
  displayName: __t.string(),
  state: __t.string(),
  joinedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type HostedRoomPeer = __Infer<typeof HostedRoomPeer>;

export const HostedRoomSignal = __t.object("HostedRoomSignal", {
  signalId: __t.string(),
  roomId: __t.string(),
  fromPeerId: __t.string(),
  toPeerId: __t.string(),
  signalKind: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type HostedRoomSignal = __Infer<typeof HostedRoomSignal>;

