import type { WorkbenchField } from '../fieldTypes';

export const ABILITY_FIELDS: WorkbenchField[] = [
  {
    id: 'targeting',
    label: 'Targeting',
    section: 'abilities',
    kind: 'ability',
    path: 'abilities[selected].targeting',
    controlId: 'workbench-ability-targeting',
    input: 'select',
    options: [
      { value: 'free-aim', label: 'Free aim' },
      { value: 'aim-assist', label: 'Aim assist' },
    ],
  },
  {
    id: 'damage',
    label: 'Damage',
    section: 'abilities',
    kind: 'ability',
    path: 'abilities[selected].damage',
    controlId: 'workbench-ability-damage',
    input: 'number',
    min: 0,
    step: 1,
  },
  {
    id: 'cooldownTicks',
    label: 'Cooldown ticks',
    section: 'abilities',
    kind: 'ability',
    path: 'abilities[selected].cooldownTicks',
    controlId: 'workbench-ability-cooldown',
    input: 'number',
    min: 0,
    step: 1,
  },
  {
    id: 'range',
    label: 'Range',
    section: 'abilities',
    kind: 'ability',
    path: 'abilities[selected].range',
    controlId: 'workbench-ability-range',
    input: 'number',
    min: 0.1,
    step: 0.1,
  },
  {
    id: 'radius',
    label: 'Radius',
    section: 'abilities',
    kind: 'ability',
    path: 'abilities[selected].radius',
    controlId: 'workbench-ability-radius',
    input: 'number',
    min: 0.05,
    step: 0.05,
  },
  {
    id: 'color',
    label: 'Color',
    section: 'abilities',
    kind: 'ability',
    path: 'abilities[selected].color',
    controlId: 'workbench-ability-color',
    input: 'color',
  },
];
