import type { WorkbenchField } from '../fieldTypes';

export const PLAYER_FIELDS: WorkbenchField[] = [
  {
    id: 'movementMode',
    label: 'Movement mode',
    section: 'player',
    kind: 'rules',
    path: 'player.movement.mode',
    controlId: 'workbench-movement-mode',
    input: 'select',
    options: [
      { value: 'twinStick', label: 'Twin stick' },
      { value: 'tank', label: 'Tank' },
      { value: 'platform', label: 'Platform' },
    ],
  },
  {
    id: 'aimMode',
    label: 'Aim mode',
    section: 'player',
    kind: 'rules',
    path: 'player.aim.mode',
    controlId: 'workbench-aim-mode',
    input: 'select',
    options: [
      { value: 'free', label: 'Free' },
      { value: 'facing', label: 'Facing' },
    ],
  },
  {
    id: 'playerSpeed',
    label: 'Speed',
    section: 'player',
    kind: 'rules',
    path: 'player.speed',
    controlId: 'workbench-player-speed',
    input: 'number',
    min: 1,
    step: 0.1,
  },
  {
    id: 'playerDamping',
    label: 'Damping',
    section: 'player',
    kind: 'rules',
    path: 'player.damping',
    controlId: 'workbench-player-damping',
    input: 'number',
    min: 0,
    step: 0.1,
  },
  {
    id: 'playerMaxHp',
    label: 'Max HP',
    section: 'player',
    kind: 'rules',
    path: 'player.maxHp',
    controlId: 'workbench-player-hp',
    input: 'number',
    min: 1,
    step: 1,
  },
  {
    id: 'tankTurn',
    label: 'Tank turn deg/s',
    section: 'player',
    kind: 'rules',
    path: 'player.movement.turnSpeedDegrees',
    controlId: 'workbench-tank-turn',
    input: 'number',
    min: 30,
    step: 10,
    visibleWhen: { fieldId: 'movementMode', equals: 'tank' },
  },
  {
    id: 'tankReverse',
    label: 'Tank reverse',
    section: 'player',
    kind: 'rules',
    path: 'player.movement.reverseMultiplier',
    controlId: 'workbench-tank-reverse',
    input: 'number',
    min: 0,
    max: 1,
    step: 0.05,
    visibleWhen: { fieldId: 'movementMode', equals: 'tank' },
  },
  {
    id: 'platform.gravity',
    label: 'Gravity',
    section: 'player',
    kind: 'rules',
    path: 'player.movement.platform.gravity',
    controlId: 'workbench-platform-gravity',
    input: 'number',
    min: 1,
    step: 1,
    visibleWhen: { fieldId: 'movementMode', equals: 'platform' },
  },
  {
    id: 'platform.jumpVelocity',
    label: 'Jump velocity',
    section: 'player',
    kind: 'rules',
    path: 'player.movement.platform.jumpVelocity',
    controlId: 'workbench-platform-jump',
    input: 'number',
    min: 1,
    step: 0.5,
    visibleWhen: { fieldId: 'movementMode', equals: 'platform' },
  },
  {
    id: 'platform.airControl',
    label: 'Air control',
    section: 'player',
    kind: 'rules',
    path: 'player.movement.platform.airControl',
    controlId: 'workbench-platform-air',
    input: 'number',
    min: 0,
    max: 1,
    step: 0.05,
    visibleWhen: { fieldId: 'movementMode', equals: 'platform' },
  },
  {
    id: 'platform.maxFallSpeed',
    label: 'Max fall speed',
    section: 'player',
    kind: 'rules',
    path: 'player.movement.platform.maxFallSpeed',
    controlId: 'workbench-platform-fall',
    input: 'number',
    min: 1,
    step: 1,
    visibleWhen: { fieldId: 'movementMode', equals: 'platform' },
  },
  {
    id: 'platform.groundProbeDistance',
    label: 'Ground probe',
    section: 'player',
    kind: 'rules',
    path: 'player.movement.platform.groundProbeDistance',
    controlId: 'workbench-platform-probe',
    input: 'number',
    min: 0.01,
    step: 0.01,
    visibleWhen: { fieldId: 'movementMode', equals: 'platform' },
  },
];
