// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptJoinHostedRoomReducer from "../accept_join_hosted_room_reducer";
import CloseHostedRoomReducer from "../close_hosted_room_reducer";
import CreateHostedRoomReducer from "../create_hosted_room_reducer";
import HeartbeatHostedRoomReducer from "../heartbeat_hosted_room_reducer";
import LeaveHostedRoomReducer from "../leave_hosted_room_reducer";
import PruneHostedRoomsReducer from "../prune_hosted_rooms_reducer";
import RequestJoinHostedRoomReducer from "../request_join_hosted_room_reducer";
import SendHostedRoomSignalReducer from "../send_hosted_room_signal_reducer";

export type AcceptJoinHostedRoomParams = __Infer<typeof AcceptJoinHostedRoomReducer>;
export type CloseHostedRoomParams = __Infer<typeof CloseHostedRoomReducer>;
export type CreateHostedRoomParams = __Infer<typeof CreateHostedRoomReducer>;
export type HeartbeatHostedRoomParams = __Infer<typeof HeartbeatHostedRoomReducer>;
export type LeaveHostedRoomParams = __Infer<typeof LeaveHostedRoomReducer>;
export type PruneHostedRoomsParams = __Infer<typeof PruneHostedRoomsReducer>;
export type RequestJoinHostedRoomParams = __Infer<typeof RequestJoinHostedRoomReducer>;
export type SendHostedRoomSignalParams = __Infer<typeof SendHostedRoomSignalReducer>;

